# # -- 코드를 입력하세요
# # SELECT
# # M.MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# # FROM
# # MEMBER_PROFILE M,
# # REST_REVIEW R
# # WHERE
# # M.MEMBER_ID = R.MEMBER_ID and
# # M.MEMBER_ID IN 
# # (
# # SELECT 
# # ranked.MEMBER_ID
# # FROM
# # (
# # SELECT R.MEMBER_ID, RANK() OVER (ORDER BY count(R.MEMBER_ID) DESC) AS 'RANKING' from MEMBER_PROFILE M, REST_REVIEW R WHERE M.MEMBER_ID = R.MEMBER_ID  group by R.MEMBER_ID
# # ) ranked
# # WHERE ranked.RANKING = 1
# # ) 
# # ORDER BY
# # REVIEW_DATE, REVIEW_TEXT



# WITH TEMP AS 
# (
#     SELECT MEMBER_ID, RANK() OVER(order by count(MEMBER_ID) DESC)
#     from REST_REVIEW
#     group by MEMBER_ID
# )
# SELECT
# MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM
# MEMBER_PROFILE,
# (
#     SELECT MEMBER_ID, RANK() OVER(order by count(MEMBER_ID) DESC) AS C
#     from REST_REVIEW
#     group by MEMBER_ID
# ) ranked
# ,REST_REVIEW
# WHERE
# MEMBER_PROFILE.MEMBER_ID = ranked.MEMBER_ID
# and
# ranked.MEMBER_ID = REST_REVIEW.MEMBER_ID
# and
# ranked.C = 1
# order by
# REVIEW_DATE, REVIEW_TEXT

WITH ranked_members AS (
    SELECT 
        RR.MEMBER_ID,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKED
    FROM REST_REVIEW RR
    GROUP BY RR.MEMBER_ID
)
SELECT 
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    ranked_members RM
JOIN REST_REVIEW RR ON RR.MEMBER_ID = RM.MEMBER_ID
JOIN MEMBER_PROFILE MP ON MP.MEMBER_ID = RM.MEMBER_ID
WHERE 
    RM.RANKED = 1
ORDER BY 
    REVIEW_DATE ASC,
    REVIEW_TEXT ASC;
